package org.qcwala1.dfsproject.qcplatform.qcinfo;

public enum QCFilter {
	ID, FS_ID,
	// REOPENED_FS_IDS
	DESCRIPTION, CURRENT_STATUS, DEVELOPER, TESTER, SEVERITY, MODULE_ID, REMARKS, READYTOTEST, QCTRACK,
	// GT -greater than
	GT_P_ETA, GT_C_ETA, GT_UPLOAD_DATE, GT_EXTERNAL_REOPEN_COUNTER, GT_INTERNAL_REOPEN_COUNTER,
	// e = equal
	E_P_ETA, E_C_ETA, E_UPLOAD_DATE, E_EXTERNAL_REOPEN_COUNTER, E_INTERNAL_REOPEN_COUNTER,
	// lt - less than
	LT_P_ETA, LT_C_ETA, LT_UPLOAD_DATE, LT_EXTERNAL_REOPEN_COUNTER, LT_INTERNAL_REOPEN_COUNTER;
}
